### PR TITLE
regenerate vpc to update initialism members

### PR DESCRIPTION
**Pull request by brycahta**
* Regenerate with latest `code-generator` and `runtime`
* Update initialism fields to correct casing

### CODE REVIEW

**Comment by brycahta** [comment]
Will run `build-controller-release` to create the helm chart in a separate PR. This should resolve ec2-release-test failing

**Review by jaypipes — APPROVED** [review]
:+1:

**Comment by jaypipes** [comment]
@vijtrip2 for repos where we have not yet run `make build-controller-release` (like this one), there is no `helm` directory and the release test fails :) Can you work with @brycahta to handle that for ec2-controller repo?

**Comment by vijtrip2** [comment]
> @vijtrip2 for repos where we have not yet run `make build-controller-release` (like this one), there is no `helm` directory and the release test fails :) Can you work with @brycahta to handle that for ec2-controller repo?

@jaypipes Yes, I added that as the part in script to fail if no helm directory is present. Is that not correct?
Currently I advised @brycahta to run build-controller-release script to make the release-test pass.

**Comment by brycahta** [comment]
> Currently I advised @brycahta to run build-controller-release script to make the release-test pass.

Helm chart here: https://github.com/aws-controllers-k8s/ec2-controller/pull/3

**Comment by vijtrip2** [comment]
Merged PR #3 , please rebase from main and then hopefully this branch will pass all the tests too :)

**Pull request merged**
