### PR TITLE
NAT Gateway test fix

### PR DESCRIPTION
**Pull request by LikithaVemulapalli**
Description of changes:

- Added `Resource.Synced` checks after creating the resource in order to check whether resource is synced or not.
- Added wait times after deleting the resource.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by LikithaVemulapalli** [comment]
After viewing logs from the failed test runs, error doesn't seem related to resource being synced or not, in this PR e2e test logs we can clearly see that resource is being synced, and we do use same `simple_nat_gateway` for the remaining NAT Gateway test cases. The error seems to be related to `test_crud_tags` as per the tests failures in other PR's. Posted this PR in order to check whether tests are passing or not as I'm unable to reproduce this error when I run e2e tests locally with my changes.

**Comment by brycahta** [comment]
After some more deep dive, 2 controller logs stand out:

1. **Context:** creating ElasticIP
```
2022-10-12T20:15:27.279Z	DEBUG	ackrt	< r.Sync	{"account": "713338758733", "role": "", "region": "us-west-2", "kind": "ElasticIPAddress", "namespace": "default", "name": "nat-gateway-eip-0mh3110hhxr1aymf", "is_adopted": false, "generation": 1, "error": "AddressLimitExceeded: The maximum number of addresses has been reached.\n\tstatus code: 400, request id: 493b5aee-52aa-4c28-8d19-10b058c13ee1"}
```
* I have submitted requests to increase default limits on multiple resources including EIP (some of these require manual approvals)

> I'm unable to reproduce this error when I run e2e tests locally with my changes.

* I know these tests run on multiple threads and AFAIK the thread count is not static but based on the machine. It's possible that this cannot be reproduced locally due to fewer number of threads executing the tests (i.e. enough time to create/delete EIPs before hitting limits) and/or testing on local account could have different limits.

2. **Context:** deleting ElasticIP
```
2022-10-12T20:18:52.124Z	ERROR	controller.elasticipaddress	Reconciler error	{"reconciler group": "ec2.services.k8s.aws", "reconciler kind": "ElasticIPAddress", "name": "nat-gateway-eip-ggpqngiia8bo2ouv", "namespace": "default", "error": "AuthFailure: You do not have permission to access the specified resource.\n\tstatus code: 400, request id: ecbb2ace-3413-4f0c-98ec-399d3cf21d5b"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
```

* This could explain why EIPs hang around the test account from time to time, but I don't see the e2e test role lacking permissions. Further deep dive shows this error can happen if you try to release the EIP prior to deleting a NAT Gateway ([docs](https://aws.amazon.com/premiumsupport/knowledge-center/ec2-troubleshoot-elastic-ip-addresses/)). However, it seems like NAT Gateway is getting deleted properly so I'd expect this to eventually reconcile. Will re-check logs after increasing limits.

**Review by brycahta — APPROVED** [review]
/lgtm

**Pull request merged**
